import { apiClient } from './apiConfig';

const API_BASE_URL = `/service`;

export interface Service {
  id: number;
  code: number;
  title: string;
  description: string;
  price: number;
  createdAt?: string;
  updatedAt?: string;
}

// Type for creation, as the ID is generated by the backend
export type ServiceData = Omit<Service, 'id' | 'createdAt' | 'updatedAt'>;

export const serviceService = {
  getAllServices: async (): Promise<Service[]> => {
    const response = await apiClient.get(API_BASE_URL);
    return response.data;
  },

  getServiceById: async (id: number): Promise<Service> => {
    const response = await apiClient.get(`${API_BASE_URL}/${id}`);
    return response.data;
  },

  getServiceByCode: async (code: number): Promise<Service> => {
    const services = await serviceService.getAllServices();
    const service = services.find(s => s.code === code);
    if (!service) {
      throw new Error(`Service with code ${code} not found`);
    }
    return service;
  },

  createService: async (serviceData: ServiceData): Promise<Service> => {
    const response = await apiClient.post(`${API_BASE_URL}/create`, serviceData);
    return response.data;
  },

  updateService: async (id: number, serviceData: Partial<ServiceData>): Promise<Service> => {
    const response = await apiClient.patch(`${API_BASE_URL}/${id}/update`, serviceData);
    return response.data;
  },

  deleteService: async (id: number): Promise<void> => {
    await apiClient.delete(`${API_BASE_URL}/${id}/delete`);
  },
};
