import axios from 'axios';

const API_BASE_URL = `${import.meta.env.VITE_API_BASE_URL}/service`;

export interface Service {
  id: number;
  code: number;
  title: string;
  description: string;
  price: number;
}

// Type for creation, as the ID is generated by the backend
export type ServiceData = Omit<Service, 'id'>;

export const serviceService = {
  getAllServices: async (): Promise<Service[]> => {
    const response = await axios.get(API_BASE_URL);
    return response.data;
  },

  getServiceByCode: async (code: number): Promise<Service> => {
    const response = await axios.get(`${API_BASE_URL}/${code}`);
    return response.data;
  },

  createService: async (serviceData: ServiceData): Promise<Service> => {
    const response = await axios.post(`${API_BASE_URL}/create`, serviceData);
    return response.data;
  },

  updateService: async (code: number, serviceData: Partial<ServiceData>): Promise<Service> => {
    const response = await axios.patch(`${API_BASE_URL}/${code}/update`, serviceData);
    return response.data;
  },

  deleteService: async (code: number): Promise<void> => {
    await axios.delete(`${API_BASE_URL}/${code}/delete`);
  },
};
