import axios from 'axios';

const API_BASE_URL = `${import.meta.env.VITE_API_BASE_URL}/vehicle`;

export interface Vehicle {
  id: number;
  board: string;
  model: string;
  brand: string;
  year: number;
  createdAt?: string;
  updatedAt?: string;
}

// Type for creation, as the ID is generated by the backend
export type VehicleData = Omit<Vehicle, 'id' | 'createdAt' | 'updatedAt'>;

export const vehicleService = {
  getAllVehicles: async (): Promise<Vehicle[]> => {
    const response = await axios.get(API_BASE_URL);
    return response.data;
  },

  getVehicleById: async (id: number): Promise<Vehicle> => {
    const response = await axios.get(`${API_BASE_URL}/${id}`);
    return response.data;
  },

  createVehicle: async (vehicleData: VehicleData): Promise<Vehicle> => {
    const response = await axios.post(`${API_BASE_URL}/create`, vehicleData);
    return response.data;
  },

  updateVehicle: async (id: number, vehicleData: Partial<VehicleData>): Promise<Vehicle> => {
    const response = await axios.patch(`${API_BASE_URL}/${id}/update`, vehicleData);
    return response.data;
  },

  deleteVehicle: async (id: number): Promise<void> => {
    await axios.delete(`${API_BASE_URL}/${id}/delete`);
  },
};